version: "3"
services:
    python:
        build:
            context: ./python
            dockerfile: Dockerfile.txt
        container_name: python_ptt
        tty: true
        stdin_open: true
        depends_on:
            - db
        ports:
            - 80:80
            - 5000:5000
    
    db:
        image: mysql
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: eric
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: pttdb
        volumes:
            - "./sql/sqldb:/var/lib/mysql"
            - "./sql/sql_sh:/docker-entrypoint-initdb.d"
        ports:
            - 3306:3306


    adminer:
        image: adminer
        restart: always
        ports:
           - 8080:8080
    
